### ISSUE TITLE
Pull for stree ends up in wrong subdir

### ISSUE THREAD

**Issue by ml31415** [deliciousinsights/git-stree#22]
I gave `stree` a try today, as the basic concept sounds quite fine. Initial splitting and pushing to a remote host with a new bare repository worked fine, unfortunately pulling back changes into the main repo failed in a way, that the changes ended up in a totally unrelated directory. Even worse, the whole subtree got replicated in this other unrelated folder. I had tried to follow the instructions, nevertheless of course, I might have gotten something wrong here, so sorry in advance for that case. The code is closed, so unfortunately I can't directly reference it here. The source tree looks something like:

```
/
/core/...
/utils/...
...
```

This is the sequence of instructions I had used:

```
# on the remote host :
git init --bare utils

# locally in repo root
git stree split utils -P utils code@remotehost:utils
# seemd to work fine
cd ..
git clone code@remotehost:utils utilstest
# everything there, edit edit, commit
git push
# seems to be fine, back to main repo
cd ../testproj
git stree pull utils
```

Now the whole content of utils got replicated into /core/comm/alice and the content there deleted:

```
[master e1bb1e8] [STree] Pulled stree 'utils'
 140 files changed, 12572 insertions(+), 287817 deletions(-)
 create mode 100644 core/comm/alice/__init__.py
 create mode 100644 core/comm/alice/accumarray.py
 delete mode 100644 core/comm/alice/ai.aiml
 delete mode 100644 core/comm/alice/alice.aiml
....
✔ STree 'utils' pulled, 1 update(s) committed.
```
Anything wrong with the path spec there? Any further information I can provide on this, without fully disclosing the whole repo? I was using the latest checokut for this test. This is the stree config:

```
$ git config --list|grep stree
remote.stree-utils.url=code@remotehost:utils
remote.stree-utils.fetch=+refs/heads/master:refs/remotes/stree-utils/master
stree.utils.prefix=utils
stree.utils.branch=master
stree.utils.latest-sync=e1bb1e8
branch.stree-backports-utils.remote=stree-utils
branch.stree-backports-utils.merge=refs/heads/master
```

**Comment by tdd** [comment]
Hey Michael,

Woah, that's a serious bug. At first I was concerned that your prefix starting with a slash, hence being absolute, may be the reason, but nope, as your local config says, I'm normalizing this.

Two questions for you:

1. Can you confirm the code in `utilstest`, cloned from the stree `split`'s pushed refs, indeed only included the code from `utils/` and its filtered log?
2. Does the source tree in `core` look very much like the one in `utils` (file names, paths, etc.)?

See, `git stree` currently does a `git merge -s subtree`, not a `git merge -X subtree=<prefix>`, as the latter form sometimes b0rks and I couldn't isolate why yet. It's a shame, because the latter form uses no path heuristics, whilst the former does; hence my question about path similarities inside `core/`.

Best,

**Comment by ml31415** [comment]
The initial /utils as -P argument was a typo when I had copied this back from the console.

**Comment by ml31415** [comment]
What seems to fail is only the last merge with the subtree strategy. This is what fails in the script as well as manually:

```
git fetch stree-utils
git merge -s subtree --squash stree-utils/master
```
After this command, the alice folder is messed up, and the mess marked for commit. Why it picks exactly this folder ... no idea. Seems to be quite arbitrary to me. Maybe a git bug? I'm running 2.1.0 from Ubuntu stable.

**Comment by csemrau** [comment]
I stumbled over the same bug when I tried stree last week, and found basically the same fix. :+1:

**Comment by csemrau** [comment]
I don't know if it is the bugfix that causes it, but I found a very annoying problem: When I pull via stree, any file that was deleted in the stree-repo is NOT removed in the local repository. I have to remove it by hand and commit the deletion.

**Comment by tdd** [comment]
Oooooh. I'll have to see whether that still occurs when we get around to applying a more general pull-related fix pertaining to initial stree histories setup.

**Comment by davidparker** [comment]
Wondering if this same bug is related to mine:

git stree split extensions -P app/extensions https://username@bitbucket.org/username/extensionsrepo.git

I thought this was going to create a folder called app/extensions, but instead it ignores my path, and then slaps everything in root, and then switches me to a spree branch it has created.

Is this the same issue,   or do i need to create a new issue.

this is the name of the zip file and stree I am running:  tdd-git-stree-c0fbce3

thanks

**Comment by tdd** [comment]
Hey there,

It sounds like you're confusing `split` and `add`.  `split` is designed 
to take an *existing* subdir you've been developing inside the main repo 
so far, and turn it into an stree.  The repo you're mentioning is 
assumed to be empty and will get its first push due to the split.

OTOH, `add` is there to inject a new stree locally, in a subdir, from an 
existing dedicated repo.

Am I missing something of your use case here?

Best,

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Comment by davidparker** [comment]
Hi 

Yeah  app/extensions is already in my system,   its is essentially a SPA system, built with durandal JS,   But I have some shared modules in extensions,   However,  I need to build variations of this system, and wanted to share this across all my variations and not have the pain of having to copy any fixes / patches or upgrades to every other UI variation.

So my code existed,   I just went and created a remote repo called extensionsrepo,   then pasted in that command, expecting this to be linked up as a subtree.  instead what it seemed to do  was create some subtree branch,  removed the directory extensions and then put all the files into my main root.

I checked to make sure I was on the latest commit from you,  and I was.   Then checked the dates and assumed it may be a while between updates.

I did eventually get it working,   but what i had to do was remove the subtree,  then use add, then move the code from main repo, to new repo,  push to new repo, pull in old repo with git stree pull extensions

this then populated my folder with files,   I now just open the new repo in atom   make changes,  and again just do git stree pull extensions and all seems to work fine.

I did come to make a ticket / report as an issue  but there seemed to be a couple of tickets that refer to items been put into the root, rather than into the directory as requested, and did not want to clog the stack with another ticket, that then has to be linked up to issue XX

All of the above including the switching etc  is all within my main  / existing branch, and not inside any new stree/git repo   if that helps

thanks

Dave

**Comment by tdd** [comment]
Hey,

Le 12/11/15 00:17, magic a écrit :
> Yeah app/extensions is already in my system, its is essentially a SPA
> system, built with durandal JS, But I have some shared modules in
> extensions, However, I need to build variations of this system, and
> wanted to share this across all my variations and not have the pain of
> having to copy any fixes / patches or upgrades to every other UI variation.
>
> So my code existed, I just went and created a remote repo called
> extensionsrepo, then pasted in that command, expecting this to be linked
> up as a subtree. instead what it seemed to do was create some subtree
> branch, removed the directory extensions and then put all the files into
> my main root.

Indeed, and that's nominal.  However, if it works properly, it shouldn't 
leave you on the backport branch, but take you back to your original 
branch.  Perhaps the split command encountered an error?  What did the 
output say?

At any rate, you can checkout your previous branch manually and get your 
entire worktree back ;-)

> I did come to make a ticket / report as an issue but there seemed to be
> a couple of tickets that refer to items been put into the root, rather
> than into the directory as requested, and did not want to clog the stack
> with another ticket, that then has to be linked up to issue XX

That's OK, it's up to us to triage the issues and mark dups; we'll do 
that when we tackle significant work on git-stree again, hopefully 
sometime in December.

Best,

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Comment by davidparker** [comment]
Output was the usual success message as far as I remember  and yes,  I had
branched first,  then did it,  so was easy just to delete branch and try
again,  no errors though,  thanks
