### ISSUE TITLE
Conflict after stree pull

### ISSUE THREAD

**Issue by thomaslevesque** [deliciousinsights/git-stree#39]
I was giving git-stree a try, because it seemed to be a good alternative to git-subtree. But even in my very simple scenario, I ran into a conflict:

```
both added:      lib/sub/README
```

The conflicted file looks like this:

```
My super library

<<<<<<< HEAD
hahaha
=======
>>>>>>> stree-sub/master
```

In the "sub" repo, I just removed the line containing "hahaha". In the container repo, I didn't make any change, so there shouldn't be a conflict. What am I doing wrong?

Here's my complete test scenario:

- Create a "main" repo (the container), add a "hello.txt" file to it, and commit it
- Create a "sub.git" bare repo
- Create a "sub" repo, add a README file to it, commit and push to sub.git
- In main, add a subtree for sub:
```
git stree add sub -P lib/sub ../sub.git
```
- Still in main, make an edit to "hello.txt" and commit it
- In sub, make an edit to README.txt, commit it and push it
- In main, pull the changes from sub:
```
git stree pull sub
```

The tree looks like this:

```
test-stree
├───main
│   │   hello.txt
│   │   
│   └───lib
│       └───sub
│               README
│               
├───sub
│       README
│       
└───sub.git
```

I didn't make any edit to README in the main repo, so why is there a conflict?

**Comment by thomaslevesque** [comment]
For completeness, here's the history for main:
```
8d02fd4 (HEAD, master) Edited hello.txt
6214710 [STree] Added stree 'sub' in lib/sub
d344ac8 Initial commit
```

And for sub:
```
8eb3d80 (HEAD, origin/master, master) Removed 'hahaha'
2e492da Initial commit
```

**Comment by thomaslevesque** [comment]
I can resolve the conflict manually of course, but then, everytime I pull new changes from sub, I get a similar conflict on a file I didn't touch...

**Comment by tdd** [comment]
Hey Thomas,

You’re correct, I *can* reproduce this.  Clearly there are issues with 
Git's subtree merge.  This behavior happens even when attempting a 
regular merge with `-X subtree=lib/sub`, which is as explicit as it goes.

We're currently investigating an alley based on an early `git merge -s 
ours`, that might help fix a number of pull-related issues.  Stay tuned.

Best,


-- 
Christophe Porteneuve
Founder & CTO, Delicious Insights
christophe@delicious-insights.com
+33 662 059 656

**Comment by stela5** [comment]
Ref: https://github.com/tdd/git-stree/pull/23

I fixed it for my needs by adding a merge strategy option: https://gist.github.com/anonymous/5ca8bc8abd59c7006370#file-git-stree-L458

**Comment by BobTB** [comment]
I made a simple test, two remote repositories (#1, #2). Clone #1, git stree #2 in the subfolder. 
git stree push works as expected. 
If I edit a file in #2, add and commit and then do the git stree pull #2 I get the conflict in this edited file.

This is sadly useless for any edits made upstream in the library I want to stree in the main repo I am running now. I thought that this will solve all my problems as it looked very promising. Sadly it does not work at all, every edit in the lib is conflicting with the untouched files in the imported stree... :(

**Comment by stela5** [comment]
There are more changes than just that one line in the gist.  Did you use the entire gist version?

**Comment by BobTB** [comment]
Yes, I just copied it over to old, I have also seen that it makes .gitstree file etc.. but for me it still creates the conflict merge

**Comment by dhuantes** [comment]
Just an added note to throw into the mix and in preparation for the holiday fix...<crosses fingers>.  The "standard" stree (TDD's) was working great for me pushing and pulling from shared repo(s) on multiple libraries to and from multiple containers.  But the last pull I did pulled in code from the wrong stree.  I can't put code out as an example so will need to come up with one that I can post on github that replicates this (TODO).  I reviewed the gist code but there were so many changes I felt a little uncomfortables with the -Xours and -Xtheirs options so just did a manual git merge -X subtree="<subt-tree-name" stree-<stree-name>/<branch>.  And that "worked" but this option on the recursive strategy seems to always flag any change to any file in the repository as a conflict.  I tried this with multiple "test repositories" and the same thing every time.  Then I realized this is probably why the -Xours and the -Xtheirs options were created in the first place and why the gist includes two different pull commands (pullours/pulltheirs).  But again, if their really is a conflict I'd rather be the one making the call on which code I am going to keep.  So for now I've opted to just used the subtree strategy (TDD's original) but before I do a stree pull I create a branch specifically for that purpose so I can see what is happening and can revert back to the pre-pull state if there is a problem.  Thus far I've only had one instance where I needed to use the recursive strategy with the -X subtree option and, of course, I had to manually resolve conflicts on that pull.  But believe me this is still better than the subtree's push and pull approach.  Especially since the push takes forever traversing every commit.

**Comment by dhuantes** [comment]
Below is a bash script that demonstrates a very simple case where the both the subtree strategy (e.g. -s subtree) and the recursive strategy with the subtree option (e.g. -s recursive -X subtree="\<sub-tree-name\>") detect a conflict where there really should not be a conflict.  Which makes me think that the bug lies in the git merge command code itself.  
```
#! /bin/bash

#This script replicates an example of when the `git stree pull command`
#detects a conflict that should not be a conflict.

echo "Checking for existence of temp_stree_test directory...."
if [ -d "temp_stree_test" ]
then
	echo "Deleting temp_stree_test directory...."
	rm -rf temp_stree_test
fi
echo "Making directory 'temp_stree_test'...."
mkdir temp_stree_test

cd temp_stree_test

mkdir container_app

mkdir stree_lib

cd container_app

echo "Create ReadMe.txt file..."
echo "This is a container example..." > ReadMe.txt

echo "Create git repository with ReadMe.txt file..."
git init

git add ReadMe.txt

git commit -m "Initial Commit"

echo "Create git repository with another ReadMe.txt file for repo that will later be stree...."
cd ../stree_lib
cd ../stree_lib

echo "This is library repository..." > ReadMe.txt

git init

git add ReadMe.txt

git commit -m "Initial Commit"

echo "Move back into container repository to add stree...."
cd ../container_app

git stree add stree_lib -P stree_lib ../stree_lib master

echo "Move back into standalone stree repo and make a change..."
cd ../stree_lib

echo "Appending new line of text to ReadMe.txt..."
echo "\rHere is a new line of text" >> ReadMe.txt
git add ReadMe.txt

git commit -m "Added new Line of text"

echo "Moving back into container to perform stree pull..."
cd ../container_app

git stree pull stree_lib

git status

```

**Comment by stela5** [comment]
@dhuantes You are correct regarding my inclusion of pullours/pulltheirs

**Comment by tdd** [comment]
Hey guys. This is likely due to the same issue as in #22 (and others, I guess; de-duping this right now). We're working on a whole rewrite that should do away with all this. Keeping this open until the matching test passes on the new codebase.
