### ISSUE TITLE
git stree pull goes to wrong directory

### ISSUE THREAD

**Issue by TrevorMills** [deliciousinsights/git-stree#46]
I have this:

    me$ git stree list
    • remote.stree-foo.url [''] <=> git@bitbucket.org:myusername/foo.git@
    • remote.stree-bar.url [''] <=> git@bitbucket.org:myusername/bar.git@
    me$ cat .git/config | grep "the lines I want"
    [remote "stree-foo"]
        url = git@bitbucket.org:myusername/foo.git
        fetch = +refs/heads/develop:refs/remotes/stree-foo/develop
    [stree "foo"]
        prefix = wp-content/plugins/foo
        branch = develop
        latest-sync = 0d04e0c
    [branch "stree-backports-foo"]
        remote = stree-foo
        merge = refs/heads/develop
    [remote "stree-bar"]
        url = git@bitbucket.org:myusername/bar.git
        fetch = +refs/heads/refactor:refs/remotes/stree-bar/refactor
    [stree "bar"]
        prefix = wp-content/plugins/bar
        branch = refactor
        latest-sync = 8bbc425
    [branch "stree-backports-bar"]
        remote = stree-bar
        merge = refs/heads/refactor

There were remote updates to bar that included new files that arrived in that repo via a `git merge master` on the `refactor` branch.  When I ran `git stree pull bar` today, I got this:

    me$ git stree pull bar
    [master e26ed77] [STree] Pulled stree 'bar'
    1 file changed, 1 insertion(+)
    create mode 100644 wp-content/plugins/*foo*/path/to/new-file.js
    ✔ STree 'bar' pulled, 49 update(s) committed.

It pulled the changes, but it wrote the new files to the `foo` directory.  

I was deep in the middle of something and had to move on quickly, so instead I did `git stree rm bar` and added it in again fresh.  Tonight, as I'm writing you this, I'm not able to reproduce.  Alas.  But it definitely happened repeatedly.  

Have you seen anything like this before? 

Thanks
Trevor

**Comment by tdd** [comment]
Hey Trevor,

Yes, this is a known issue. It's likely due to stree currently using the subtree strategy (`-s subtree`) without a specific path, instead of the recursive strategy with subtree option (`-X subtree=wp-content/plugins/bar`).

When multiple strees have similar code structure, the heuristics of Git's subtree strategy pick any of the similar matches.

The intended full rewrite of stree (which has a number of issues) is currently on hold, as discussion is ongoing with the guys behind the similar-purpose [git subrepo](https://github.com/ingydotnet/git-subrepo/) tool to figure out whether we should instead focus on their project, which is much further along than we are. Perhaps have a look there?
