### ISSUE TITLE
Manage subtree versions

### ISSUE THREAD

**Issue by orodbhen** [deliciousinsights/git-stree#8]
So how do you specify which version of a sub-project to add? You would have to pull in the projects history in order to select a sha or tag. But pulling tags could create a conflict with the container. 

You could create a temporary branch, checkout a specific tag, and then squash merge into the master. But then how do you update it?

Have you already devised a way for handling this?

**Comment by tdd** [comment]
Hey!

`pull` assumes a branch, true. Initial `add` shouldn't care too much if you specify a tag or SHA instead of a branch name, I'd have to double-check.

This might need a new subcommand, specifically for setting to / rebasing over a specific SHA instead of a branch's tip. Or an extra optional param for `pull`, maybe.

In the meantime, totally doable by hand of course. Just fetch your subtree remote and do a rebase -X subtree=prefix over the SHA/tag you're after. Should work a charm!
